version: '2.4'

services:
  postgres:
    image: postgres:11.6
    ports:
      - 54321:5432
#    environment:
#      - POSTGRES_DB=django_test_db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
    volumes:
      - pg-data:/var/lib/postgresql/data
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
volumes:
  pg-data:
