site_name: root_app
site_description: Simple django project
repo_url: https://github.com/yass_arafat/django-io
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/yass_arafat">yass_arafat</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
